//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.04 at 11:39:41 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://legkodymov.name/ws/country-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package name.legkodymov.ws.country_service;
